### ISSUE TITLE
[Task] Allow configuration of file upload directory

### ISSUE THREAD

**Issue by jiekang** [cryostatio/jfr-datasource#5]
The file uploads feature currently uploads file into the `<working-directory>/file-uploads`. The application should support configuration of this to an alternate directory, possibly via a System property setting.

**Comment by andrewazores** [comment]
This is set in [application.properties](https://github.com/cryostatio/jfr-datasource/blob/cdb477f20eaad6da347f10b8f6403e637acc5c28/src/main/resources/application.properties#L1). Quarkus allows such properties to be overridden by Java System property using the same key-value scheme (`-Dquarkus.http.body.uploads-directory=/some/other/directory` in this case), or by environment variable (`QUARKUS_HTTP_BODY_UPLOADS_DIRECTORY="/some/other/directory"`). Since these are implemented and supported by Quarkus, I don't think there is anything in particular to be done within jfr-datasource to allow this type of configuration.
